name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libgexiv2-dev meson valac
    - name: Build
      run: |
        meson build
        ninja -C build
    - name: Test Metadata
      run: bash tests.sh
    - name: Install
      run: |
        ninja -C build install
