name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apt update
        apt install -y exif librsvg2-bin meson
    - name: Test Metadata
      run: bash tests.sh
    - name: Build
      run: |
        meson build
        ninja -C build
        ninja -C build install
