name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    container:
      image: elementary/docker:next-unstable

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apt update
        apt install -y exif librsvg2-bin meson
    - name: Test Metadata
      run: bash tests.sh

    - name: Build
      run: |
        meson build
        ninja -C build install

    - name: Build (Early Access)
      run: |
        meson configure -Dearly_access=true
        ninja -C build install
